baseURL = 'https://runsondata.com/'
languageCode = 'en-GB'
title = 'Runs on Data'
theme = 'paper'

[markup.goldmark.renderer]
  unsafe = true

[params]
  name = "Callum McMahon"
  bio = "Machine Learning Engineering for fun"
  avatar = "/avatar.png"

[caches]
  [caches.images]
    dir = ':cacheDir/images'